"""empty message

Revision ID: 0061175c6ba9
Revises: 6f8ac7c6d0e9
Create Date: 2023-03-29 01:13:48.109160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0061175c6ba9'
down_revision = '6f8ac7c6d0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###
