"""empty message

Revision ID: 14599e5cb164
Revises: 6c8507caf7e4
Create Date: 2023-06-04 23:42:26.199750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14599e5cb164'
down_revision = '6c8507caf7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_mobil', sa.String(length=20), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('status_mobil')

    # ### end Alembic commands ###
