"""empty message

Revision ID: 15261f3eacf3
Revises: b7cb147254b3
Create Date: 2023-05-10 11:08:46.449326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15261f3eacf3'
down_revision = 'b7cb147254b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
