"""empty message

Revision ID: 1e26d8f00b1c
Revises: 83af7a8fb8db
Create Date: 2023-05-26 23:19:39.367842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e26d8f00b1c'
down_revision = '83af7a8fb8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('dp')

    # ### end Alembic commands ###
