"""empty message

Revision ID: 277da4c4855b
Revises: f3947b34a95c
Create Date: 2023-05-13 11:27:55.300706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277da4c4855b'
down_revision = 'f3947b34a95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pemesanan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pemesanan', ['pemesanan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pemesanan_id')

    # ### end Alembic commands ###
