"""empty message

Revision ID: 2908bb615d8f
Revises: 6833e8996fa9
Create Date: 2023-03-27 00:46:13.742195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2908bb615d8f'
down_revision = '6833e8996fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_kembali', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('tgl_kembali')

    # ### end Alembic commands ###
