"""empty message

Revision ID: 2f177b3272b0
Revises: 2f8551983629
Create Date: 2023-05-30 23:22:55.283190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f177b3272b0'
down_revision = '2f8551983629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])
        batch_op.drop_column('photo')
        batch_op.drop_column('dp')
        batch_op.drop_column('pemesanan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pemesanan_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'pemesanan', ['pemesanan_id'], ['id'])
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###
