"""empty message

Revision ID: 2f8551983629
Revises: 5b77b724b595
Create Date: 2023-05-30 23:21:31.428371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8551983629'
down_revision = '5b77b724b595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])
        batch_op.drop_column('pemesanan_id')
        batch_op.drop_column('photo')
        batch_op.drop_column('dp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('pemesanan_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'pemesanan', ['pemesanan_id'], ['id'])
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###
