"""empty message

Revision ID: 339f4d6855b8
Revises: b60860329de0
Create Date: 2023-05-10 11:22:52.600993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339f4d6855b8'
down_revision = 'b60860329de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merek', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_column('merek')

    # ### end Alembic commands ###
