"""empty message

Revision ID: 377f53cbe2d5
Revises: 4cd7c2fde05d
Create Date: 2023-05-10 12:41:49.611924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377f53cbe2d5'
down_revision = '4cd7c2fde05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])

    # ### end Alembic commands ###
