"""empty message

Revision ID: 3ec972f08565
Revises: c7211ea98c7a
Create Date: 2023-03-27 12:39:37.288403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec972f08565'
down_revision = 'c7211ea98c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_sewa', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('denda_per_hari', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('denda_per_hari')
        batch_op.drop_column('harga_sewa')

    # ### end Alembic commands ###
