"""empty message

Revision ID: 4d3514acfb4b
Revises: 719d6bc7269c
Create Date: 2023-04-04 02:12:37.282206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3514acfb4b'
down_revision = '719d6bc7269c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengembalian')
    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_kembali', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.drop_column('tgl_kembali')

    op.create_table('pengembalian',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nama', sa.INTEGER(), nullable=False),
    sa.Column('tgl_kembali', sa.DATETIME(), nullable=False),
    sa.Column('kondisi_mobil', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pemesanan_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
