"""empty message

Revision ID: 50c588e1efd2
Revises: 277da4c4855b
Create Date: 2023-05-13 11:28:59.880410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c588e1efd2'
down_revision = '277da4c4855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pemesanan', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pemesanan', ['id_pemesanan'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_pemesanan')

    # ### end Alembic commands ###
