"""empty message

Revision ID: 534178b28ca1
Revises: 7a6147cf5463
Create Date: 2023-06-01 17:52:18.984571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534178b28ca1'
down_revision = '7a6147cf5463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_kembali_aktual', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('tgl_kembali_aktual')

    # ### end Alembic commands ###
