"""empty message

Revision ID: 5b82dfb22c0a
Revises: 95ea9655388f
Create Date: 2023-05-27 16:10:13.969191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b82dfb22c0a'
down_revision = '95ea9655388f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sisa_harga', sa.Integer(), nullable=True))

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sisa_harga', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('sisa_harga')

    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('sisa_harga')

    # ### end Alembic commands ###
