"""empty message

Revision ID: 5fe50e2ac45f
Revises: 81bfac3bb1ee
Create Date: 2023-03-27 12:44:39.942733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe50e2ac45f'
down_revision = '81bfac3bb1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_sewa', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('denda_per_hari', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('denda_per_hari')
        batch_op.drop_column('harga_sewa')

    # ### end Alembic commands ###
