"""empty message

Revision ID: 6088b899e9a5
Revises: c7025fd0c94b
Create Date: 2023-05-13 11:17:57.684523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6088b899e9a5'
down_revision = 'c7025fd0c94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pemesanan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pemesanan', ['pemesanan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pemesanan_id')

    # ### end Alembic commands ###
