"""empty message

Revision ID: 60dbc81886ce
Revises: 
Create Date: 2023-03-10 13:10:46.158204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dbc81886ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merek', sa.String(length=50), nullable=False),
    sa.Column('harga_sewa', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_mobil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merek', sa.String(length=50), nullable=False),
    sa.Column('nomor_plat', sa.String(length=10), nullable=False),
    sa.Column('warna', sa.String(length=10), nullable=False),
    sa.Column('harga_sewa', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('mobil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pemesanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Integer(), nullable=False),
    sa.Column('merek', sa.String(length=50), nullable=False),
    sa.Column('harga_sewa', sa.Integer(), nullable=False),
    sa.Column('jumlah_hari', sa.Integer(), nullable=False),
    sa.Column('tgl_sewa', sa.DateTime(), nullable=False),
    sa.Column('tgl_kembali', sa.DateTime(), nullable=False),
    sa.Column('total_biaya', sa.Integer(), nullable=False),
    sa.Column('mobil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pemesanan')
    op.drop_table('detail_mobil')
    op.drop_table('user')
    op.drop_table('mobil')
    # ### end Alembic commands ###
