"""empty message

Revision ID: 64205da3ad17
Revises: 6e502973e438
Create Date: 2023-05-17 00:28:03.193584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64205da3ad17'
down_revision = '6e502973e438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_plat', sa.String(length=10), nullable=False))

    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_plat', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('nomor_plat')

    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.drop_column('nomor_plat')

    # ### end Alembic commands ###
