"""empty message

Revision ID: 68cefd084e48
Revises: 5fe50e2ac45f
Create Date: 2023-03-27 22:41:18.641013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cefd084e48'
down_revision = '5fe50e2ac45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denda_per_hari', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mobil_id')

    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.drop_column('denda_per_hari')

    # ### end Alembic commands ###
