"""empty message

Revision ID: 6c8507caf7e4
Revises: 33c0b7d641ee
Create Date: 2023-06-04 17:51:19.705848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8507caf7e4'
down_revision = '33c0b7d641ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
