"""empty message

Revision ID: 6e502973e438
Revises: 3e5f39b50490
Create Date: 2023-05-13 16:50:11.136173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e502973e438'
down_revision = '3e5f39b50490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.alter_column('tgl_sewa',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('tgl_kembali',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.alter_column('tgl_kembali',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tgl_sewa',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
