"""empty message

Revision ID: 6f57599538d6
Revises: 5b82dfb22c0a
Create Date: 2023-05-28 23:01:56.559755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f57599538d6'
down_revision = '5b82dfb22c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denda_per_hari', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('harga_sewa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_hari', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_biaya', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.drop_column('total_biaya')
        batch_op.drop_column('dp')
        batch_op.drop_column('jumlah_hari')
        batch_op.drop_column('harga_sewa')
        batch_op.drop_column('denda_per_hari')

    # ### end Alembic commands ###
