"""empty message

Revision ID: 6f8ac7c6d0e9
Revises: cd77de6cb0f8
Create Date: 2023-03-29 01:13:04.719712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8ac7c6d0e9'
down_revision = 'cd77de6cb0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.Integer(), nullable=True))
        batch_op.alter_column('pemesanan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pemesanan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###
