"""empty message

Revision ID: 716658e5e85a
Revises: 55f0da2c3276
Create Date: 2023-03-27 23:43:55.838992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716658e5e85a'
down_revision = '55f0da2c3276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_hari', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('jumlah_hari')

    # ### end Alembic commands ###
