"""empty message

Revision ID: 719d6bc7269c
Revises: 8927f5aa8994
Create Date: 2023-03-29 16:11:46.107636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719d6bc7269c'
down_revision = '8927f5aa8994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denda_per_hari', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('denda_per_hari')

    # ### end Alembic commands ###
