"""empty message

Revision ID: 77d6c04d8d7d
Revises: 377f53cbe2d5
Create Date: 2023-05-10 12:44:07.492642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d6c04d8d7d'
down_revision = '377f53cbe2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.alter_column('mobil_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.alter_column('mobil_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
