"""empty message

Revision ID: 7a6147cf5463
Revises: 2f177b3272b0
Create Date: 2023-05-30 23:28:54.647980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6147cf5463'
down_revision = '2f177b3272b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sisa_harga', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status_mobil', sa.String(length=20), nullable=True))
        batch_op.drop_column('photo')

    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('sisa_harga')
        batch_op.drop_column('status')
        batch_op.drop_column('status_mobil')
        batch_op.drop_column('dp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('status_mobil', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('sisa_harga', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('status_mobil')
        batch_op.drop_column('status')
        batch_op.drop_column('sisa_harga')

    # ### end Alembic commands ###
