"""empty message

Revision ID: 81bfac3bb1ee
Revises: 3ec972f08565
Create Date: 2023-03-27 12:42:54.564673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bfac3bb1ee'
down_revision = '3ec972f08565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_sewa', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('denda_per_hari', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('denda_per_hari')
        batch_op.drop_column('harga_sewa')

    # ### end Alembic commands ###
