"""empty message

Revision ID: 83054b9c3ae1
Revises: 9c822e280131
Create Date: 2023-03-27 01:33:57.421991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83054b9c3ae1'
down_revision = '9c822e280131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('total_denda')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_denda', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
