"""empty message

Revision ID: 83af7a8fb8db
Revises: d73ad58e0b43
Create Date: 2023-05-26 18:23:27.860446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83af7a8fb8db'
down_revision = 'd73ad58e0b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_plat', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.drop_column('nomor_plat')

    # ### end Alembic commands ###
