"""empty message

Revision ID: 8927f5aa8994
Revises: 0061175c6ba9
Create Date: 2023-03-29 01:21:10.426291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8927f5aa8994'
down_revision = '0061175c6ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengembalian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Integer(), nullable=False),
    sa.Column('tgl_kembali', sa.DateTime(), nullable=False),
    sa.Column('kondisi_mobil', sa.String(length=50), nullable=False),
    sa.Column('pemesanan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.alter_column('pemesanan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.alter_column('pemesanan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('pengembalian')
    # ### end Alembic commands ###
