"""empty message

Revision ID: 91851803dc9d
Revises: e19caa000716
Create Date: 2023-06-01 21:03:41.004361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91851803dc9d'
down_revision = 'e19caa000716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_disewa', schema=None) as batch_op:
        batch_op.drop_column('filter_date')

    # ### end Alembic commands ###
