"""empty message

Revision ID: 9ecba3f8111f
Revises: 68cefd084e48
Create Date: 2023-03-27 22:44:57.188736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecba3f8111f'
down_revision = '68cefd084e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###
