"""empty message

Revision ID: b414ca393731
Revises: 6641b8ce85fd
Create Date: 2023-05-27 15:46:49.961971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414ca393731'
down_revision = '6641b8ce85fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_sewa', sa.DateTime(), nullable=False))
        batch_op.drop_column('tanggal_transaksi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_transaksi', sa.DATETIME(), nullable=False))
        batch_op.drop_column('tgl_sewa')

    # ### end Alembic commands ###
