"""empty message

Revision ID: b7cb147254b3
Revises: 4d3514acfb4b
Create Date: 2023-05-10 10:58:41.663086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cb147254b3'
down_revision = '4d3514acfb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobil_dipinjam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_penyewa', sa.String(length=50), nullable=False),
    sa.Column('mobil_id', sa.Integer(), nullable=False),
    sa.Column('tgl_sewa', sa.DateTime(), nullable=False),
    sa.Column('tgl_kembali', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobil_dipinjam')
    # ### end Alembic commands ###
