"""empty message

Revision ID: c0be19e16cf9
Revises: 5339092290f5
Create Date: 2023-05-13 11:23:26.483752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0be19e16cf9'
down_revision = '5339092290f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pemesanan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('pemesanan_fk', 'pemesanan', ['pemesanan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.drop_constraint('pemesanan_fk', type_='foreignkey')
        batch_op.drop_column('pemesanan_id')

    # ### end Alembic commands ###
