"""empty message

Revision ID: c7025fd0c94b
Revises: 77d6c04d8d7d
Create Date: 2023-05-13 11:16:55.636235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7025fd0c94b'
down_revision = '77d6c04d8d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pemesanan_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'pemesanan', ['pemesanan_id'], ['id'])
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])
        batch_op.drop_column('pemesanan_id')

    # ### end Alembic commands ###
