"""empty message

Revision ID: c91a2998ff86
Revises: 63b0d60c836a
Create Date: 2023-03-26 15:51:00.721245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91a2998ff86'
down_revision = '63b0d60c836a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pemesanan', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
