"""empty message

Revision ID: cdac3a982b71
Revises: 35c278058eb9
Create Date: 2023-03-29 00:43:28.674330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdac3a982b71'
down_revision = '35c278058eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengembalian')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengembalian',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nama', sa.INTEGER(), nullable=False),
    sa.Column('tgl_kembali', sa.DATETIME(), nullable=False),
    sa.Column('kondisi_mobil', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pemesanan_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
