"""empty message

Revision ID: e05c66472cd5
Revises: 14599e5cb164
Create Date: 2023-06-09 00:18:42.294403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05c66472cd5'
down_revision = '14599e5cb164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
