"""empty message

Revision ID: e853a59db111
Revises: c91a2998ff86
Create Date: 2023-03-26 20:38:47.098619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e853a59db111'
down_revision = 'c91a2998ff86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengembalian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Integer(), nullable=False),
    sa.Column('tgl_kembali', sa.DateTime(), nullable=False),
    sa.Column('kondisi_mobil', sa.String(length=50), nullable=False),
    sa.Column('pemesanan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Integer(), nullable=False),
    sa.Column('tanggal_transaksi', sa.DateTime(), nullable=False),
    sa.Column('metode_pembayaran', sa.String(length=20), nullable=False),
    sa.Column('total_biaya', sa.Integer(), nullable=False),
    sa.Column('denda', sa.Integer(), nullable=True),
    sa.Column('pemesanan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('pengembalian')
    # ### end Alembic commands ###
