"""empty message

Revision ID: f3947b34a95c
Revises: c0be19e16cf9
Create Date: 2023-05-13 11:25:41.485616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3947b34a95c'
down_revision = 'c0be19e16cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_mobil_dipinjam')
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pemesanan_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pemesanan_fk', 'pemesanan', ['pemesanan_id'], ['id'])
        batch_op.drop_column('mobil_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobil_dipinjam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobil_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('pemesanan_fk', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mobil', ['mobil_id'], ['id'])
        batch_op.drop_column('pemesanan_id')

    op.create_table('_alembic_tmp_mobil_dipinjam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mobil_id', sa.INTEGER(), nullable=True),
    sa.Column('tgl_sewa', sa.DATETIME(), nullable=False),
    sa.Column('tgl_kembali', sa.DATETIME(), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nama', sa.VARCHAR(length=50), nullable=False),
    sa.Column('merek', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pemesanan_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], name='pemesanan_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
