"""empty message

Revision ID: f8bb56a6f05d
Revises: 50c588e1efd2
Create Date: 2023-05-13 11:30:28.462099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bb56a6f05d'
down_revision = '50c588e1efd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobil_disewa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('merek', sa.String(length=50), nullable=False),
    sa.Column('tgl_sewa', sa.DateTime(), nullable=False),
    sa.Column('tgl_kembali', sa.DateTime(), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('pemesanan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pemesanan_id'], ['pemesanan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobil_disewa')
    # ### end Alembic commands ###
